export const supportedLanguages = [
  { code: 'en', flag: '🇺🇸', name: 'English' },
  { code: 'es', flag: '🇪🇸', name: 'Español' },
];

const en = {
  brand: 'SmartAgenda', language: 'Language', currentSchool: 'Current school', workspace: 'Workspace', manage: 'Manage', coordinator: 'Coordinator', profile: 'Profile', profileMenu: 'Open profile menu', editProfile: 'Edit Profile', profileSettings: 'Profile settings', openProfile: 'Open profile', editSchoolProfile: 'Edit School Profile', schoolProfileSettings: 'School profile settings', signOut: 'Sign out',
  dashboard: 'Dashboard', calendar: 'Calendar', sessions: 'Reading Sessions', families: 'Families', teachers: 'Teachers', students: 'Students', notifications: 'Notifications', history: 'History', settings: 'Settings',
  appearance: 'Appearance', theme: 'Theme', theme_light: 'Light', theme_dark: 'Dark', theme_system: 'System default', dateFormat: 'Date format', timeFormat: 'Time format', time_12h: '12-hour', 'time_12h-padded': '12-hour padded', time_24h: '24-hour', privacySecurity: 'Privacy & security', cookiePreferences: 'Allow optional cookies', cookieHelp: 'Allow optional cookies used for preferences and product improvement.',
  search: 'Search', closeSearch: 'Close search', searchPlaceholder: 'Search sessions, families...', searchReady: 'Search is ready for live session and family data.', openNotifications: 'Open notifications', notificationPending: 'Teacher confirmation is pending.', notificationFailed: 'WhatsApp volunteer request failed.', viewAllNotifications: 'View all notifications',
  goodMorning: 'Good morning, {{name}}', welcome: "Let's get the next reading session ready.", newSession: 'New Reading Session', assignVolunteer: 'Assign volunteer', sendNotification: 'Send notification',
  back: 'Back', save: 'Save', cancel: 'Cancel', sessionStatus: 'Session status', scheduled: 'Scheduled', confirmed: 'Confirmed', cancelled: 'Cancelled', coordinatorNote: 'Coordinator note', volunteer: 'Volunteer', channel: 'Channel', message: 'Message', groupName: 'Group name', saveSession: 'Session changes saved.', assignmentSaved: 'Volunteer assignment saved.', notificationQueued: 'Notification queued successfully.', manageReading: 'Manage Reading Session', sessionOps: 'Session operations', assignTitle: 'Assign Volunteer', coverage: 'Coverage', sendTitle: 'Send Notification', communication: 'Communication', communicationHelp: 'Prepare a message for teachers or family volunteers.',
  selectSchool: 'Select school', addNewSchool: 'Add new school', schoolName: 'School name', timezone: 'Timezone', locale: 'Locale', name: 'Name', profileHelp: 'Update your profile information and avatar.', schoolProfileHelp: 'Update the selected school profile.', saveChanges: 'Save Changes', saving: 'Saving...', changesSaved: 'Changes saved successfully.', saveError: 'Unable to save changes. Please try again.', selectGrade: 'Select a registered grade', addNewGrade: 'Add new grade', selectGroup: 'Select a registered group', addNewGroup: 'Add new group name', registerFamily: 'Register family', familyRegistrationTitle: 'Register Family', familyName: 'Family name', guardian: 'Guardian', child: 'Child', fullName: 'Full name', email: 'Email', relationship: 'Relationship', languages: 'Languages', school: 'School', grade: 'Grade', register: 'Register', registering: 'Registering...', familySuccess: 'Family registered successfully.', familyError: 'The family could not be saved.', privacyNote: 'Family and child information is protected and visible only to authorized school coordinators and the household.', noGrades: 'No grades registered for this school yet.', noGroups: 'No groups registered for this grade yet.',
};

const es = {
  ...en,
  language: 'Idioma', currentSchool: 'Escuela actual', workspace: 'Espacio de trabajo', manage: 'Administrar', coordinator: 'Coordinador', profile: 'Perfil', profileMenu: 'Abrir menú del perfil', editProfile: 'Editar perfil', profileSettings: 'Configuración del perfil', openProfile: 'Abrir perfil', editSchoolProfile: 'Editar perfil de la escuela', schoolProfileSettings: 'Configuración de la escuela', signOut: 'Cerrar sesión',
  dashboard: 'Panel', calendar: 'Calendario', sessions: 'Sesiones de lectura', families: 'Familias', teachers: 'Maestros', students: 'Estudiantes', notifications: 'Notificaciones', history: 'Historial', settings: 'Configuración', search: 'Buscar', closeSearch: 'Cerrar búsqueda', searchPlaceholder: 'Buscar sesiones, familias...', searchReady: 'La búsqueda está lista para sesiones y familias.', openNotifications: 'Abrir notificaciones', notificationPending: 'La confirmación del maestro está pendiente.', notificationFailed: 'Falló la solicitud por WhatsApp.', viewAllNotifications: 'Ver todas las notificaciones',
  appearance: 'Apariencia', theme: 'Tema', theme_light: 'Claro', theme_dark: 'Oscuro', theme_system: 'Predeterminado del sistema', dateFormat: 'Formato de fecha', timeFormat: 'Formato de hora', time_12h: '12 horas', 'time_12h-padded': '12 horas con cero', time_24h: '24 horas', privacySecurity: 'Privacidad y seguridad', cookiePreferences: 'Permitir cookies opcionales', cookieHelp: 'Permite cookies opcionales para preferencias y mejora del producto.',
  goodMorning: 'Buenos días, {{name}}', welcome: 'Preparemos la próxima sesión de lectura.', newSession: 'Nueva sesión de lectura', assignVolunteer: 'Asignar voluntario', sendNotification: 'Enviar notificación', back: 'Volver', save: 'Guardar', cancel: 'Cancelar', sessionStatus: 'Estado de la sesión', scheduled: 'Programada', confirmed: 'Confirmada', cancelled: 'Cancelada', coordinatorNote: 'Nota del coordinador', volunteer: 'Voluntario', channel: 'Canal', message: 'Mensaje', groupName: 'Nombre del grupo', saveSession: 'Cambios guardados.', assignmentSaved: 'Asignación guardada.', notificationQueued: 'Notificación enviada a la cola.', manageReading: 'Administrar sesión de lectura', sessionOps: 'Operaciones de sesión', assignTitle: 'Asignar voluntario', coverage: 'Cobertura', sendTitle: 'Enviar notificación', communication: 'Comunicación', communicationHelp: 'Prepara un mensaje para maestros o familias.',
  selectSchool: 'Seleccionar escuela', addNewSchool: 'Agregar nueva escuela', schoolName: 'Nombre de la escuela', timezone: 'Zona horaria', locale: 'Configuración regional', name: 'Nombre', profileHelp: 'Actualiza tu información de perfil y avatar.', schoolProfileHelp: 'Actualiza el perfil de la escuela seleccionada.', saveChanges: 'Guardar cambios', saving: 'Guardando...', changesSaved: 'Cambios guardados correctamente.', saveError: 'No se pudieron guardar los cambios. Inténtalo de nuevo.', selectGrade: 'Seleccionar un grado registrado', addNewGrade: 'Agregar nuevo grado', selectGroup: 'Seleccionar un grupo registrado', addNewGroup: 'Agregar nombre de grupo', registerFamily: 'Registrar familia', familyRegistrationTitle: 'Registrar familia', familyName: 'Nombre de la familia', guardian: 'Tutor', child: 'Estudiante', fullName: 'Nombre completo', email: 'Correo electrónico', relationship: 'Relación', languages: 'Idiomas', school: 'Escuela', grade: 'Grado', register: 'Registrar', registering: 'Registrando...', familySuccess: 'Familia registrada correctamente.', familyError: 'No se pudo guardar la familia.', privacyNote: 'La información familiar y del estudiante está protegida y solo es visible para coordinadores autorizados y el hogar.', noGrades: 'Aún no hay grados registrados para esta escuela.', noGroups: 'Aún no hay grupos registrados para este grado.',
};

export const translations = { en, es };
